### ISSUE TITLE
Keep me signed in prompt problem

### ISSUE THREAD

**Issue by eccountable** [WaelHamze/dyn365-ce-bdd#1]
I downloaded this project and my test seems to get as far as the "keep me signed in" prompt between the login and the CRM application and then fails. I downloaded the EasyRepro source code and I can get past the login, and I have tried to replace your version of the UIAutomation assemblies with a new build from the copy I got from GitHub, but that throws an error 
"Could not load type 'OpenQA.Selenium.Support.UI.WebDriverWait' "

**Comment by eccountable** [comment]
We updated to the latest chrome web driver and that got us past the "Keep me signed in" issue.

**Comment by WaelHamze** [comment]
Thanks for sharing. This project uses the Nuget Libraries that are less frequently updated. It was working when I uploaded it initially. I'll create a fix and updated the master when I get a chance.
